# minetest.conf - настройки мапгена для Beta 1.7.3 стиля

# Размер биомов (~100 блоков)
mg_biome_np_heat = 50, 50, (100,100,100), 5349, 3, 0.5, 2.0
mg_biome_np_humidity = 50, 50, (100,100,100), 842, 3, 0.5, 2.0
mg_biome_np_heat_blend = 0, 1.5, (8,8,8), 13, 2, 1.5, 2.0
mg_biome_np_humidity_blend = 0, 1.5, (8,8,8), 90003, 2, 1.5, 2.0

# Рельеф как в Beta 1.7.3
mgv5_np_ground = 0, 40, (100,100,100), 983240, 4, 0.6, 2.0

# Простые пещеры
mgv5_cave_width = 0.09

hotbar_slots = 9